openapi: "3.0.2"
info:
  title: Puppy Shop
  version: "1.0"
servers:
  - url: localhost:10778
paths:
  /users:
    get:
      responses:
        "200":
          description: OK
    post:
      description: "register"
      responses:
        "200":
          description: OK
          
  /users/token:
    post:
      description: "login"
      responses:
        "200":
          description: OK


